#
# Generate ircd/version.c.
#
# This is the CMake port of the old ircd/version.c.SH.  It produces the same
# file: a build generation counter, a human-readable build timestamp, the
# credits block, and an MD5 checksum for every source file and public header.
#
# The checksums used to be computed by running `umkpasswd -5`, which meant
# version.c could not be built before umkpasswd was linked.  file(MD5) gives
# the identical digests without that bootstrap dependency.
#
# The one visible difference from version.c.SH is that the "Sources:" list no
# longer carries an entry for the generator itself, since version.c.SH is gone.
#
# Usage:
#   cmake -DIRCU_SOURCE_DIR=<top srcdir> -DIRCU_OUTPUT=<path> \
#         -P GenerateVersion.cmake
#

cmake_minimum_required(VERSION 3.16)

if(NOT IRCU_SOURCE_DIR OR NOT IRCU_OUTPUT)
  message(FATAL_ERROR "IRCU_SOURCE_DIR and IRCU_OUTPUT must both be set")
endif()

# ---------------------------------------------------------------------------
# Build generation: read the counter out of the previous version.c and bump it.
# ---------------------------------------------------------------------------
set(generation 0)
if(EXISTS "${IRCU_OUTPUT}")
  file(STRINGS "${IRCU_OUTPUT}" _prev REGEX "^const char \\*generation = ")
  foreach(_line IN LISTS _prev)
    if(_line MATCHES "\"([0-9]+)\"")
      set(generation "${CMAKE_MATCH_1}")
    endif()
  endforeach()
endif()
math(EXPR generation "${generation} + 1")

# Same shape as the old `date | awk` pipeline, e.g.
# "Sun Sep 7 2026 at 14:31:07 UTC".
string(TIMESTAMP creation "%a %b %d %Y at %H:%M:%S UTC" UTC)

# ---------------------------------------------------------------------------
# Checksum list
# ---------------------------------------------------------------------------
# Files that are themselves generated never carry a meaningful checksum.
set(_excluded version.c ircd_parser.c lex.yy.c chattr.tab.c)

function(_ircu_checksums out)
  set(_lines "")
  foreach(_file IN LISTS ARGN)
    get_filename_component(_name "${_file}" NAME)
    if(NOT _name IN_LIST _excluded)
      file(MD5 "${_file}" _hash)
      # umkpasswd printed "[ name: hash <rev> ]"; no file in the tree carries
      # an expanded $Id$ any more, so the revision field stays empty.
      string(APPEND _lines "    \"[ ${_name}: ${_hash}  ]\",\n")
    endif()
  endforeach()
  set(${out} "${_lines}" PARENT_SCOPE)
endfunction()

file(GLOB _sources
  "${IRCU_SOURCE_DIR}/ircd/*.c"
  "${IRCU_SOURCE_DIR}/ircd/*.l"
  "${IRCU_SOURCE_DIR}/ircd/*.y")
list(SORT _sources)

file(GLOB _headers "${IRCU_SOURCE_DIR}/include/*.h")
list(SORT _headers)

_ircu_checksums(source_sums ${_sources})
_ircu_checksums(header_sums ${_headers})

# ---------------------------------------------------------------------------
# Emit
# ---------------------------------------------------------------------------
file(WRITE "${IRCU_OUTPUT}" "\
/*
 * IRC - Internet Relay Chat, ircd/version.c
 * Copyright (C) 1990 Chelsea Ashley Dyerman
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 1, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 * This file is generated by cmake/GenerateVersion.cmake.
 * Any changes made will go away.
 */

#include \"version.h\"
#include \"patchlevel.h\"
#include \"patchlist.h\"

const char *generation = \"${generation}\";
const char *creation = \"${creation}\";
const char *version = BASE_VERSION RELEASE PATCHLEVEL PATCHLIST;

const char *infotext[] = {
    \"IRC --\",
    \"This program is free software; see LICENSE in the distribution\",
    \"\",
    \"Based on the original code written by Jarkko Oikarinen, version 2.6:\",
    \"Wiz          Jarkko Oikarinen         <jto@tolsun.oulu.fi>\",
    \"\",
    \"The main developer of version u2.9 and u2.10 was:\",
    \"Run          Carlo Wood               <carlo@runaway.xs4all.nl>\",
    \"\",
    \"The head developer of the u2.10 source tree was:\",
    \"Bleep        Thomas Helvey            <tomh@inxpress.net>\",
    \"\",
    \"The current maintainers of the u2.10 source tree are:\",
    \"Entrope      Michael Poole            <mdpoole@troilus.org>\",
    \"Kev          Kevin Mitchell           <klmitch@mit.edu>\",
    \"\",
    \"The Undernode Team Developers:\",
    \"Undernode Coders                   <coders@undernode.com>\",
    \"\",
    \"Contributors to this release:\",
    \"Kev, Isomer, Gte, Ghostwolf, Bleep\",
    \"Debugging and support:\",
    \"SeKs, Maniac-, HeKTik, OmniDynmc, Liandrin, Dianora\",
    \"Special thanks to Angel and Buff for believing in us and putting\",
    \"up with frantic late night phone calls\",
    \"\",
    \"Thanks goes to all other people who contributed to any version.\",
    \"A full listing of all coders can be found in doc/Authors in the\",
    \"source.\",
    \"\",
    \"Sources:\",
${source_sums}\
    \"\",
    \"Headers:\",
${header_sums}\
    0,
};
")
